export const AR_TRANSLATION = {
  'My Notebooks': 'دفاتري',
  'Command Bar': 'شريط الأوامر',
  'Math Panel': 'لوحة الرياضيات',
  Archive: 'الأرشيف',
  'New Folder': 'مجلد جديد',
  'New File': 'ملف جديد',
  'Notebooks Tooltip': 'انقر مرتين لفتح الموقع',
  Variables: 'متغيرات',
  Functions: 'وظائف',
  Prompt: 'اكتب أمرًا أو ابحث...',
  Preferences: 'تفضيلات',
  Theme: 'الوضع',
  Color: 'لون التمييز',
  Dark: 'مظلم',
  Light: 'فاتح',
  Language: 'اللغة',
  Hebrew: 'عبرية',
  Russian: 'الروسية',
  'Mandarin Chinese': 'الصينية الماندرين',
  Hindi: 'هندي',
  French: 'فرنسي',
  English: 'الإنجليزية',
  Arabic: 'العربية',
  Spanish: 'الأسبانية',
  Red: 'أحمر',
  Blue: 'أزرق',
  Green: 'أخضر',
  Yellow: 'أصفر',
  Purple: 'أرجواني',
  Pink: 'وردي',
  'Text Block': 'إضافة كتلة نصية',
  'Math Block': 'إضافة كتلة رياضية',
  'Graph Block': 'إضافة كتلة رسم بياني',
  'Draw Block': 'إضافة كتلة رسم',
  Divider: 'إضافة فاصل',
  Clear: 'مسح الصفحة',
  Save: 'حفظ',
  'Add Tag': 'إضافة وسم',
  'Placeholder 1': 'للبدء',
  'Placeholder 2': 'انقر على رمز الدفتر على اليمين',
  'Placeholder 3': 'وافتح / أنشئ ملفًا',
  'Placeholder Or': 'أو',
  'Modal 1': 'محو محتوى الصفحة؟',
  'Modal 2': 'يوجد ملف جديد بالفعل',
  'Modal 3': 'يوجد مجلد جديد بالفعل',
  'Modal 4': 'هذا الاسم موجود بالفعل',
  Cancel: 'إلغاء',
  OK: 'موافق',
  Saved: 'تم حفظ الملف!',
  'Save Error': 'خطأ أثناء حفظ الملف',
  'Text Placeholder': 'إدراج نص...',
};
