export const EN_TRANSLATION = {
  'My Notebooks': 'Notebooks',
  'Command Bar': 'Command Bar',
  'Math Panel': 'Math Panel',
  Archive: 'Archive',
  'New Folder': 'New Folder',
  'New File': 'New File',
  'Notebooks Tooltip': 'Double click to open location',
  Variables: 'Variables',
  Functions: 'Functions',
  Prompt: 'Type a command or search...',
  Preferences: 'Preferences',
  Theme: 'Theme',
  Color: 'Accent Color',
  Dark: 'Dark Theme',
  Light: 'Light Theme',
  Language: 'Language 🌍',
  Hebrew: 'Hebrew - עברית',
  Russian: 'Russian - Русский',
  English: 'English',
  Arabic: 'Arabic - العربية',
  Spanish: 'Spanish - Español',
  Hindi: 'Hindi - हिंदी',
  'Mandarin Chinese': 'Mandarin Chinese - 中文普通话',
  French: 'French - Française',
  Red: 'Red',
  Blue: 'Blue',
  Green: 'Green',
  Yellow: 'Yellow',
  Purple: 'Purple',
  Pink: 'Pink',
  'Text Block': 'Add Text Block',
  'Math Block': 'Add Math Block',
  'Graph Block': 'Add Graph Block',
  'Draw Block': 'Add Draw Block',
  Divider: 'Add Divider',
  Clear: 'Clear Page',
  Save: 'Save',
  'Add Tag': 'Add Tag',
  'Placeholder 1': 'To begin',
  'Placeholder 2': 'Click on the notebook icon on your left',
  'Placeholder 3': 'and open/create a file',
  'Placeholder Or': 'or',
  'Modal 1': 'Clear page content?',
  'Modal 2': 'A new file already exists',
  'Modal 3': 'A new folder already exists',
  'Modal 4': 'This name already exists',
  'Modal 5': 'You cannot move this file here!',
  Cancel: 'Cancel',
  OK: 'OK',
  Saved: 'File saved!',
  'Save Error': 'Error while saving file',
  'Text Placeholder': 'Insert text...',
  Press: 'Press',
  'Delete Item': 'on item to delete it',
  'Rename Item': 'on item to rename it',
};
