export const ES_TRANSLATION = {
  'My Notebooks': 'Mis Cuadernos',
  'Command Bar': 'Barra de Comandos',
  'Math Panel': 'Panel de Matemáticas',
  Archive: 'Archivo',
  'New Folder': 'Nueva Carpeta',
  'New File': 'Nuevo Archivo',
  'Notebooks Tooltip': 'Haz doble clic para abrir la ubicación',
  Variables: 'Variables',
  Functions: 'Funciones',
  Prompt: 'Escriba un comando o busque...',
  Preferences: 'Preferencias',
  Theme: 'Tema',
  Color: 'Color de Acento',
  Dark: 'Tema Oscuro',
  Light: 'Tema Claro',
  Language: 'Idioma 🌍',
  Hebrew: 'Hebreo - עברית',
  Russian: 'Ruso - Русский',
  English: 'Inglés - English',
  Arabic: 'Árabe - العربية',
  Spanish: 'Español',
  French: 'Francés - Française',
  Hindi: 'hindi - हिंदी',
  'Mandarin Chinese': 'Chino mandarín - 中文普通话',
  Red: 'Rojo',
  Blue: 'Azul',
  Green: 'Verde',
  Yellow: 'Amarillo',
  Purple: 'Morado',
  Pink: 'Rosado',
  'Text Block': 'Agregar Bloque de Texto',
  'Math Block': 'Agregar Bloque de Matemáticas',
  'Graph Block': 'Agregar Bloque de Gráfico',
  'Draw Block': 'Agregar Bloque de Dibujo',
  Divider: 'Agregar Divisor',
  Clear: 'Limpiar Página',
  Save: 'Guardar',
  'Add Tag': 'Agregar Etiqueta',
  'Placeholder 1': 'Para comenzar',
  'Placeholder 2': 'Haz clic en el icono del cuaderno a tu izquierda',
  'Placeholder 3': 'y abre/crea un archivo',
  'Placeholder Or': 'o',
  'Modal 1': '¿Borrar contenido de la página?',
  'Modal 2': 'Ya existe un nuevo archivo',
  'Modal 3': 'Ya existe una nueva carpeta',
  'Modal 4': 'Este nombre ya existe',
  'Modal 5': '¡No puede mover este archivo aquí!',
  Cancel: 'Cancelar',
  OK: 'OK',
  Saved: '¡Archivo guardado!',
  'Save Error': 'Error al guardar archivo',
  'Text Placeholder': 'Inserte texto...',
  Press: 'Prensa',
  'Delete Item': 'en el elemento para eliminarlo',
  'Rename Item': 'en el elemento para cambiarle el nombre',
};
