export const FR_TRANSLATION = {
    'My Notebooks': 'Mes carnets',
    'Command Bar': 'Barre de commande',
    'Math Panel': 'Panneau mathématique',
    Archive: 'Archivo',
    'New Folder': 'Nouveau dossier',
    'New File': 'Nouveau fichier',
    'Notebooks Tooltip': `Double-cliquez pour ouvrir l'emplacement`,
    Variables: 'Variables',
    Functions: 'Les fonctions',
    Prompt: 'Tapez une commande ou recherchez...',
    Preferences: 'Préférences',
    Theme: 'Thème',
    Color: `Couleur d'accentuation`,
    Dark: 'Mode sombre',
    Light: 'Mode lumière',
    Language: 'Langue',
    Hebrew: 'Hébreu',
    Russian: 'Russe',
    English: 'Anglaise',
    Arabic: 'Arabe',
    'Mandarin Chinese': 'Chinois Mandarin',
    French: 'Française',
    Red: 'Rouge',
    Blue: 'Bleu',
    Green: 'Vert',
    Yellow: 'Jaune',
    Purple: 'Violet',
    Pink: 'Rose',
    'Text Block': 'Ajouter un bloc de texte',
    'Math Block': 'Ajouter un bloc mathématique',
    'Graph Block': 'Ajouter un bloc graphique',
    'Draw Block': 'Ajouter un bloc de dessin',
    Divider: 'Ajouter un diviseur',
    Clear: 'Effacer la page',
    Save: 'Enregistrer le fichier',
    'Add Tag': 'Ajouter une étiquette',
    'Placeholder 1': 'Pour commencer',
    'Placeholder 2': `Cliquez sur l'icône du bloc-notes à votre gauche`,
    'Placeholder 3': 'et ouvrir/créer un fichier',
    'Placeholder Or': 'ou',
    'Modal 1': 'Effacer le contenu de la page ?',
    'Modal 2': 'Un nouveau fichier existe déjà',
    'Modal 3': 'Un nouveau dossier existe déjà',
    'Modal 4': 'Ce nom existe déjà',
    Cancel: 'Annuler',
    OK: 'OK',
    Saved: 'Fichier enregistré !',
    'Save Error': `Erreur lors de l'enregistrement du fichier`,
    'Text Placeholder': 'Insérer du texte...',
  };
  