export const HE_TRANSLATION = {
  'My Notebooks': 'המחברות שלי',
  'Command Bar': 'חיפוש ופקודות',
  'Math Panel': 'זיכרון מתמטי',
  Archive: 'הארכיון שלי',
  'New Folder': 'תיקייה חדשה',
  'New File': 'קובץ חדש',
  'Notebooks Tooltip': 'לחצו פעמיים כדי לפתוח את התיקייה',
  Variables: 'משתנים',
  Functions: 'פונקציות',
  Prompt: 'הקלידו פקודה או חפשו...',
  Preferences: 'העדפות משתמש',
  Theme: 'ערכת נושא',
  Color: 'צבע נושא',
  Dark: 'מצב חושך',
  Light: 'מצב אור',
  Language: 'שפה',
  Hebrew: 'עברית',
  Russian: 'רוסית',
  English: 'אנגלית',
  Spanish: 'ספרדית',
  Arabic: 'ערבית',
  Red: 'אדום',
  Blue: 'כחול',
  Green: 'ירוק',
  Yellow: 'צהוב',
  Purple: 'סגול',
  Pink: 'ורוד',
  'Text Block': 'הוספת בלוק טקסט',
  'Math Block': 'הוספת בלוק מתמטי',
  'Graph Block': 'הוספת בלוק גרפי',
  'Draw Block': 'הוספת בלוק ציור',
  Divider: 'הוספת קו מפריד',
  Clear: 'ניקוי הדף',
  Save: 'שמירה',
  'Add Tag': 'הוספת תגית',
  'Placeholder 1': 'כדי להתחיל',
  'Placeholder 2': 'לחצו על כפתור המחברות בצד ימין',
  'Placeholder 3': 'ובחרו/צרו קובץ',
  'Placeholder Or': 'או',
  'Modal 1': 'לנקות את כל תוכן הדף?',
  'Modal 2': 'קובץ חדש כבר קיים',
  'Modal 3': 'תיקייה חדשה כבר קיימת',
  'Modal 4': 'השם הזה כבר קיים',
  Cancel: 'ביטול',
  OK: 'אישור',
  Saved: 'הקובץ נשמר!',
  'Save Error': 'התרחשה שגיאה בשמירת הקובץ',
  'Text Placeholder': 'כתבו טקסט כאן...',
};
