export const HI_TRANSLATION = {
  'My Notebooks': 'नोटबुक',
  'Command Bar': 'कमांड बार',
  'Math Panel': 'गणित पैनल',
  Archive: 'आर्काइव',
  'New Folder': 'नया फ़ोल्डर',
  'New File': 'नया फ़ाइल',
  'Notebooks Tooltip': 'जगह खोलने के लिए दोहराएँ क्लिक करें',
  Variables: 'वेरिएबल्स',
  Functions: 'फंक्शन्स',
  Prompt: 'कमांड टाइप करें या खोजें...',
  Preferences: 'प्राथमिकताएं',
  Theme: 'थीम',
  Color: 'एक्सेंट रंग',
  Dark: 'डार्क थीम',
  Light: 'लाइट थीम',
  Language: 'भाषा',
  Hebrew: 'हिब्रू',
  Russian: 'रूसी',
  English: 'अंग्रेज़ी',
  Arabic: 'अरबी',
  Spanish: 'स्पेनिश',
  'Mandarin Chinese': 'मंडारिन चाइनीज़',
  French: 'फ़्रेंच',
  Red: 'लाल',
  Blue: 'नीला',
  Green: 'हरा',
  Yellow: 'पीला',
  Purple: 'बैंगनी',
  Pink: 'गुलाबी',
  'Text Block': 'टेक्स्ट ब्लॉक जोड़ें',
  'Math Block': 'गणित ब्लॉक जोड़ें',
  'Graph Block': 'ग्राफ़ ब्लॉक जोड़ें',
  'Draw Block': 'ड्रॉ ब्लॉक जोड़ें',
  Divider: 'डिवाइडर जोड़ें',
  Clear: 'पृष्ठ साफ करें',
  Save: 'सहेजें',
  'Add Tag': 'टैग जोड़ें',
  'Placeholder 1': 'शुरू करने के लिए',
  'Placeholder 2': 'अपने बाएँ नोटबुक',
  'Placeholder 3': 'और फ़ाइल खोलें/बनाएं',
  'Placeholder Or': 'या',
  'Modal 1': 'पृष्ठ साफ़ करें?',
  'Modal 2': 'एक नया फ़ाइल पहले से ही मौजूद है',
  'Modal 3': 'एक नया फ़ोल्डर पहले से ही मौजूद है',
  'Modal 4': 'यह नाम पहले से ही मौजूद है',
  'Modal 5': 'आप इस फाइल को यहां नहीं ले जा सकते!',
  Cancel: 'रद्द करें',
  OK: 'ठीक है',
  Saved: 'फ़ाइल सहेजी गई!',
  'Save Error': 'फ़ाइल सहेजते समय त्रुटि',
  'Text Placeholder': 'टेक्स्ट डालें...',
};
