//Mandarin Chinese
export const ZH_TRANSLATION = {
  'My Notebooks': '笔记本',
  'Command Bar': '命令栏',
  'Math Panel': '数学面板',
  Archive: '存档',
  'New Folder': '新建文件夹',
  'New File': '新建文件',
  'Notebooks Tooltip': '双击打开位置',
  Variables: '变量',
  Functions: '函数',
  Prompt: '输入命令或搜索...',
  Preferences: '首选项',
  Theme: '主题',
  Color: '强调颜色',
  Dark: '暗色主题',
  Light: '亮色主题',
  Language: '语言 🌍',
  Hebrew: '希伯来语 - עברית',
  Russian: '俄语 - Русский',
  English: '英语 - English',
  Arabic: '阿拉伯语 - العربية',
  Spanish: '西班牙语 - Español',
  French: '法语 - Française',
  'Mandarin Chinese': '中文普通话',
  Hindi: '印地语 - हिंदी',
  Red: '红色',
  Blue: '蓝色',
  Green: '绿色',
  Yellow: '黄色',
  Purple: '紫色',
  Pink: '粉红色',
  'Text Block': '添加文本块',
  'Math Block': '添加数学块',
  'Graph Block': '添加图表块',
  'Draw Block': '添加绘图块',
  Divider: '添加分隔线',
  Clear: '清空页面',
  Save: '保存',
  'Add Tag': '添加标签',
  'Placeholder 1': '开始',
  'Placeholder 2': '单击左侧的笔记本图标',
  'Placeholder 3': '并打开/创建文件',
  'Placeholder Or': '或',
  'Modal 1': '清空页面内容？',
  'Modal 2': '一个新文件已经存在',
  'Modal 3': '一个新文件夹已经存在',
  'Modal 4': '此名称已经存在',
  'Modal 5': '您不能在此处移动此文件',
  Cancel: '取消',
  OK: '确定',
  Saved: '文件已保存！',
  'Save Error': '保存文件时出错',
  'Text Placeholder': '插入文本...',
  Press: '按',
  'Delete Item': '在项目上删除它',
  'Rename Item': '在项目上重命名它',
};
